mod messenger;

use std::error;
use crate::messenger::{ArchiveDetails, Message, MessengerArchive};


type IteratorItem = Result<Message, Box<dyn error::Error>>;

pub struct Parser<'a> {
    parser: Box<dyn MessengerArchive<Item=IteratorItem> + 'a>,
}


/// Read the file at the given path and try to interpret it as a valid MSN Messenger / WLM
/// conversation archive.
///
/// Archives generated by the Messenger Plus! plugin are supported too.
impl<'a> Parser<'a> {
    
    /// Generates a new parser for the given file at `path`
    pub fn new(path: &'a str) -> Result<Self, Box<dyn error::Error>> {
        Ok(Parser {
            parser: Self::get_parser(path)?,
        })
    }

    fn get_parser(path: &str) -> Result<Box<dyn MessengerArchive<Item=IteratorItem> + '_>, Box<dyn error::Error>> {
        if path.ends_with(".xml") {
            Ok(Box::new(messenger::xml_parser::XmlParser::new(path)?))
        }  else {
            Ok(Box::new(messenger::messenger_plus_parser::MessengerPlusParser::new(path)?))
        }
    }
}

impl<'a> Iterator for Parser<'a> {
    type Item = IteratorItem;

    /// Iterate through the messages in the archive
    fn next(&mut self) -> Option<Self::Item> {
        self.parser.next()
    }
}

/// Return some global details of the archive. This function must be called after the file was 
/// entirely read through the iterator.
impl<'a> MessengerArchive for Parser<'a> {
    fn details(&self) -> Option<&ArchiveDetails> {
        self.parser.details()
    }
}

#[cfg(test)]
mod tests {
    use crate::messenger::FileType;
    use super::*;

    #[test]
    fn cannot_parse_file_doesnt_exists() {
        let parser = Parser::new("archive.zip");
        assert!(parser.is_err());
    }
    
    #[test]
    fn parse_sample_file() {
        let mut parser = Parser::new("test/alice1234.xml").unwrap();
        parser.next();
        parser.next();
        assert!(parser.next().is_none());
        assert_eq!(parser.details().unwrap().file_type, FileType::XML);
        assert_eq!(parser.details().unwrap().recipient_id, "alice1234");
    }
}
